client_id = "webreader"
scope = 'SCOPE_BOSH'
redirect_uri = 'https://webreader.mytolino.com/library/'
devices_url = 'https://bosh.pageplace.de/bosh/rest/handshake/devices/list'

[additional_request_parameters]
"x_buchde.skin_id" = 17
"x_buchde.mandant_id" = 37
