# orell fuessli
[orellfuessli]
partner_id = "8"
client_id = "dte_ereader_app_01"
scope = "ebook_library"
auth_url = "https://www.orellfuessli.ch/auth/oauth2/autologin?"
token_url = "https://www.orellfuessli.ch/auth/oauth2/token"
login_url = "https://www.orellfuessli.ch/shop/home/login/login?"
reader_url = "https://webreader.mytolino.com/library/"
upload_url = "https://bosh.pageplace.de/bosh/rest/upload"
meta_url = "https://bosh.pageplace.de/bosh/rest/meta"
cover_url = "https://bosh.pageplace.de/bosh/rest/cover"
sync_data_url  = "https://bosh.pageplace.de/bosh/rest/sync-data?paths=publications,audiobooks"
delete_url  = "https://bosh.pageplace.de/bosh/rest/deletecontent"
inventory_url  = "https://bosh.pageplace.de/bosh/rest/inventory/delta"
shadow_host_id = "usercentrics-root"
cookie_deny_all_css = '.sc-gsFSXq.xZpYl'
username_field_id = 'email-input'
password_field_id = 'password-input'
submit_button_css = '.element-button-primary.button-submit'
[orellfuessli.token_header]
Host = 'www.orellfuessli.ch'
User-Agent = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'
Accept = "*/*"
Accept-Language = 'fr,fr-FR;q=0.9,en-US;q=0.8,en;q=0.7'
Accept-Encoding = 'gzip, deflate, br, zstd'
Content-Type = "application/x-www-form-urlencoded"
Content-Length = "288"
Referer = 'https://webreader.mytolino.com/'
Origin = 'https://webreader.mytolino.com'
Sec-Fetch-Dest = 'empty'
Sec-Fetch-Mode = 'cors'
Sec-Fetch-Site = 'cross-site'
Connection = 'keep-alive'
Priority = 'u=4'
TE = 'trailers'
