# orell fuessli
[orellfuessli]
partner_id = "8"
client_id = "dte_ereader_app_01"
scope = "ebook_library"
auth_url = "https://www.orellfuessli.ch/auth/oauth2/autologin?"
token_url = "https://www.orellfuessli.ch/auth/oauth2/token"
login_url = "https://www.orellfuessli.ch/shop/home/login/login?"
reader_url = "https://webreader.mytolino.com/library/"
upload_url = "https://bosh.pageplace.de/bosh/rest/upload"
meta_url = "https://bosh.pageplace.de/bosh/rest/meta"
cover_url = "https://bosh.pageplace.de/bosh/rest/cover"
sync_data_url  = "https://bosh.pageplace.de/bosh/rest/sync-data?paths=publications,audiobooks"
delete_url  = "https://bosh.pageplace.de/bosh/rest/deletecontent"
inventory_url  = "https://bosh.pageplace.de/bosh/rest/inventory/delta"
shadow_host_id = "usercentrics-root"
cookie_deny_all_css = '.sc-gsFSXq.xZpYl'
username_field_id = 'email-input'
password_field_id = 'password-input'
submit_button_css = '.element-button-primary.button-submit'
